services:
  mysql:
    image: mysql:5.5.62
    environment:
      MYSQL_DATABASE: 'izemskov'
      MYSQL_USER: 'izemskov_u'
      MYSQL_PASSWORD: '1234567890'
      MYSQL_ROOT_PASSWORD: '1234567890'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./otherfiles/izemskov.sql:/docker-entrypoint-initdb.d/izemskov.sql"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql